version: '3.8'

services:
  frontend:
    image: roma1975/try_neuro_frontend:1.0.11
    container_name: tryneuro_frontend

  backend:
    image: roma1975/try_neuro_backend:1.0.0
    container_name: tryneuro_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tryneuro_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: k918ddBi10e8_db_pass_secure

  postgres:
    image: postgres:15-alpine
    container_name: tryneuro_db_prod
    environment:
      POSTGRES_DB: tryneuro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: k918ddBi10e8_db_pass_secure
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: tryneuro_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # Позволяет Nginx обращаться к хосту (туннелю)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_prod_data:
