version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tryneuro_db_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tryneuro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
