events {} 

http {
    server {
        listen 80;

        # Обрабатываем запросы к главной странице и всему, что не /api
        location / {
            proxy_pass http://frontend; # Перенаправляем на Flutter-приложение
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Обрабатываем запросы к бэкенду
        location /api/ {
            proxy_pass http://backend:8080; # Перенаправляем на Java-бэкенд
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
