services:
  spring-ai-bot:
    container_name: tryneuro_spring_ai_bot
    build: .
    ports:
      - "8082:8082"
    env_file: .env
    networks:
      - tryneuro_network

networks:
  tryneuro_network:
    external: true
