services:
  spring-ai-bot:
    container_name: tryneuro_spring_ai_bot
    build:
      context: .
      args:
        - BUILD_PROXY=${TELEGRAM_PROXY:-}
    ports:
      - "8082:8082"
    env_file: .env
    networks:
      - tryneuro_network
    volumes:
      - /opt/whisper-host:/opt/whisper:ro

networks:
  tryneuro_network:
    external: true
