FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi httpx psycopg2-binary uvicorn

COPY main.py .

EXPOSE 8003

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"]
