server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://tryneuro_db:5432/tryneuro_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

gigachat:
  scope: ${GIGACHAT_SCOPE:GIGACHAT_API_PERS}

llm:
  local:
    url: ${LLM_LOCAL_URL:http://localhost:8083}

logging:
  level:
    com.tryneuro: DEBUG
