# ????????? ??? ????????? ??????????
spring.datasource.url=jdbc:postgresql://localhost:5433/tryneuro_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

# ???????????
logging.level.com.tryneuro.backend=DEBUG
logging.level.org.springframework.security=INFO
