server:
  port: 8081

spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true

telegram:
  api-id: ${TELEGRAM_API_ID:0}
  api-hash: ${TELEGRAM_API_HASH:none}
  # ПУТЬ ДЛЯ СЕРВЕРА (Debian/Docker): должен совпадать с объемом в docker-compose
  sessions-path: /root/.try_neuro/tg-sessions

backend:
  url: ${BACKEND_SERVICE_URL:http://localhost:8080}

logging:
  level:
    root: INFO
    it.tdlight: WARN
