name: Deploy to VPS

on:
  push:
    branches:
      - feature/telegram-mini-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/crm
            git pull origin feature/telegram-mini-app
            # Гарантируем включение BuildKit для работы кеширования Maven
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            # Собираем только изменившиеся слои
            docker-compose up -d --build
            # Очистка старых образов (не трогая кэш сборки)
            docker image prune -f
